In [2]:
import numpy as np 

## create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [4]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
## 2D array
arr2=np.array([[1,2,3,4,5],
               [1,2,3,4,5],
               [1,2,3,4,5],
               [1,2,3,4,5],
               [1,2,3,4,5],
               [1,2,3,4,5]
               ])

print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
(6, 5)
